platform :ios,'7.0'
target 'Demo' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'MJRefresh', '~> 3.0.7'
    pod 'Masonry', '~> 0.6.3'
    pod 'IQKeyboardManager', '~> 3.3.4'
    pod 'MJExtension', '~> 3.0.10'
    pod 'FMDB', '~> 2.6.2'
    pod 'DZNEmptyDataSet'
    pod 'YYText', '~> 1.0.7'
    pod 'TZImagePickerController'
end
